[versions]
kotlin = "1.9.24"
rdGen = "2024.1.1"

[libraries]
kotlinStdLib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
openTest4J = "org.opentest4j:opentest4j:1.3.0"
rdGen = { group = "com.jetbrains.rd", name = "rd-gen", version.ref = "rdGen" }

[plugins]
changelog = "org.jetbrains.changelog:2.2.0"
gradleIntelliJPlatform = "org.jetbrains.intellij.platform:2.0.0-SNAPSHOT"
gradleJvmWrapper = "me.filippov.gradle.jvm.wrapper:0.14.0"
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
