name: Release
on:
  push:
    branches:
    - main
    - renovate/**
    tags:
    - v*
  pull_request:
    branches:
    - main
  schedule:
  - cron: 0 0 * * 6
  workflow_dispatch:
jobs:
  nuget:
    permissions:
      contents: write
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v6
    - id: version
      name: Get version
      shell: pwsh
      run: echo "version=$(scripts/Get-Version.ps1 -RefName $env:GITHUB_REF)" >> $env:GITHUB_OUTPUT
    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '8.0.x'
    - run: dotnet pack --configuration Release -p:Version=${{ steps.version.outputs.version }}
    - name: Read changelog
      uses: ForNeVeR/ChangelogAutomation.action@v2
      with:
        output: ./release-notes.md
    - name: Upload artifacts
      uses: actions/upload-artifact@v7
      with:
        path: |-
          ./release-notes.md
          ./bin/Release/FVNever.Rider.Plugin.Template.${{ steps.version.outputs.version }}.nupkg
    - if: startsWith(github.ref, 'refs/tags/v')
      name: Create a release
      uses: softprops/action-gh-release@v2
      with:
        body_path: ./release-notes.md
        files: |-
          ./bin/Release/FVNever.Rider.Plugin.Template.${{ steps.version.outputs.version }}.nupkg
        name: Rider Plugin Template v${{ steps.version.outputs.version }}
    - if: startsWith(github.ref, 'refs/tags/v')
      name: Push artifact to NuGet
      run: dotnet nuget push ./bin/Release/FVNever.Rider.Plugin.Template.${{ steps.version.outputs.version }}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_TOKEN }}
